services:
  redis:
    image: redis:7-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - redis_data:/data
    networks:
      - dokploy-network

  tunnel-server:
    image: pashinov/tunnel-server:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "127.0.0.1:8001:8001"
    command: tunnel-server run --config /etc/tunnel-server/config.json
    environment:
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    depends_on:
      - redis
    networks:
      - dokploy-network

volumes:
  redis_data: {}

networks:
  dokploy-network:
    external: true
