apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-config
  namespace: nexus
data:
  config.json: |
    {
      "mqtt": {
        "host": "emqx",
        "port": 1883
      },
      "kafka": {
        "brokers": "kafka:9092"
      },
      "storage": {
        "db_path": "/var/lib/kafka-producer/client.db"
      },
      "mqtt_topic": "device/#"
    }
