apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: kafka-producer
          image: pashinov/kafka-producer:latest
          command: ["kafka-producer", "run", "-c", "/etc/kafka-producer/config.json"]
          volumeMounts:
            - name: config
              mountPath: /etc/kafka-producer
              readOnly: true
            - name: data
              mountPath: /var/lib/kafka-producer
      volumes:
        - name: config
          configMap:
            name: kafka-producer-config
        - name: data
          persistentVolumeClaim:
            claimName: kafka-producer-data
