services:
  redis:
    image: redis:7-alpine
    #restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - redis_data:/data
    networks:
      - dokploy-network

  gateway:
    image: pashinov/gateway:latest
    #restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "127.0.0.1:8000:8000"
    command: gateway run --config /etc/gateway/config.json
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIS_URL=${REDIS_URL}
    networks:
      - dokploy-network

volumes:
  redis_data: { }

networks:
  dokploy-network:
    external: true
