services:
  kafka:
    image: apache/kafka:latest
    #restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - dokploy-network

  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    command: >
      /opt/kafka/bin/kafka-topics.sh
      --bootstrap-server kafka:9092 --create --if-not-exists
      --topic device.info --partitions 3 --replication-factor 1
    networks:
      - dokploy-network

volumes:
  kafka_data: { }

networks:
  dokploy-network:
    external: true
