services:
  emqx:
    image: emqx:5.8
    #restart: always
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8883:8883"
      - "127.0.0.1:18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    environment:
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_PASSWORD}
      - EMQX_AUTHENTICATION=[]
    networks:
      - dokploy-network

volumes:
  emqx_data: { }
  emqx_log: { }

networks:
  dokploy-network:
    external: true
